package GUI;

import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.time.*;
import stage4.util.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ivans
 */
public class GUI_ReportTicketSales extends javax.swing.JFrame {

    private GUI_AnalyticsMenu guiAnalyticsMenu;
    
    public GUI_ReportTicketSales() {
        initComponents();
    }
    
    /**
     * Creates new form GUI_ReportPage
     */
    public GUI_ReportTicketSales(GUI_AnalyticsMenu guiAnalyticsMenu, LocalDate timeStart, LocalDate timeEnd) {
        initComponents();
        
        this.guiAnalyticsMenu = guiAnalyticsMenu;
        
        DefaultTableModel ticketReportModel = (DefaultTableModel) this.tableTicket.getModel();
        
        
        try (BufferedReader reader = new BufferedReader(new FileReader(Path.TICKET_SALES_REPORT_PATH))) {
            String line;

            while ((line = reader.readLine()) != null) {
                String orderInfo = line.split(";")[0];
                String seatsInfo = line.split(";")[1];

                String[] seatsPosition = seatsInfo.split(",");

                String paymentId = orderInfo.split(",")[0];

                LocalDateTime timestamp = LocalDateTime.parse(orderInfo.split(",")[1]);

                String paymentAmount = orderInfo.split(",")[2];
                String quantity = orderInfo.split(",")[3];
                String screenType = orderInfo.split(",")[4];
                String screenId = orderInfo.split(",")[5];
                String movieTitle = orderInfo.split(",")[6];
                String startTime = orderInfo.split(",")[7];
                
                if (timeStart != null && timeEnd != null && timestamp.isAfter(timeStart.atStartOfDay()) && timestamp.isBefore(timeEnd.atStartOfDay())) {

                    Object[] aRow = new Object[9];
                    
                    aRow[0] = paymentId;
                    aRow[1] = timestamp;
                    aRow[2] = paymentAmount;
                    aRow[3] = quantity;
                    aRow[4] = screenType;
                    aRow[5] = screenId;
                    aRow[6] = movieTitle;
                    aRow[7] = startTime;
                    aRow[8] = "";

                    for (int i=0; i<seatsPosition.length; i+=2) {
                        String row = seatsPosition[i].trim();
                        String col = seatsPosition[i+1].trim();

                        String pos = "(" + row + "," + col + ")";
                        aRow[8] += (pos);
                        if (i+2 != seatsPosition.length) {
                            aRow[8] += (", ");
                        }
                    }
                    
                    ticketReportModel.addRow(aRow);
                }

            }

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableTicket = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment Id", "Timestamp", "Total", "Qty", "Type", "Screen ID", "Movie", "Start", "Seats"
            }
        ));
        jScrollPane2.setViewportView(tableTicket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportTicketSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportTicketSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportTicketSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportTicketSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ReportTicketSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTicket;
    // End of variables declaration//GEN-END:variables
}
