package GUI;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ivans
 */
public class GUI_StaffAdd extends javax.swing.JFrame {

    private GUI_StaffElements guiStaffElement;
    
    /**
     * Creates new form GUI_StaffAdd
     */
    public GUI_StaffAdd() {
        initComponents();
    }

    public GUI_StaffAdd(GUI_StaffElements guiStaffElement) {
        initComponents();
        this.guiStaffElement = guiStaffElement;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffID = new javax.swing.JTextField();
        StaffName = new javax.swing.JTextField();
        lblStaffID = new javax.swing.JLabel();
        lblStaffName = new javax.swing.JLabel();
        lblStaffID1 = new javax.swing.JLabel();
        lblStaffName1 = new javax.swing.JLabel();
        hourlyRateSpinner = new javax.swing.JSpinner();
        scheduleComboBox = new javax.swing.JComboBox<>();
        lblStaffName2 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        addStaffButton = new javax.swing.JToggleButton();
        positionComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffIDActionPerformed(evt);
            }
        });

        StaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffNameActionPerformed(evt);
            }
        });

        lblStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffID.setText("Staff ID");

        lblStaffName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName.setText("Staff Name");

        lblStaffID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffID1.setText("Hourly rate ($)");

        lblStaffName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName1.setText("Schedule");

        hourlyRateSpinner.setModel(new javax.swing.SpinnerNumberModel(12, 12, 25, 1));
        hourlyRateSpinner.setAutoscrolls(true);
        hourlyRateSpinner.setDoubleBuffered(true);

        scheduleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afternoon shift (12:00-18:00)", "Night shift (18:00-24:00)" }));
        scheduleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleComboBoxActionPerformed(evt);
            }
        });

        lblStaffName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName2.setText("Position");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        addStaffButton.setText("Add staff");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });

        positionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ticket staff", "Food staff" }));
        positionComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(returnButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(lblStaffID)
                            .addGap(40, 40, 40)
                            .addComponent(StaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(lblStaffName)
                            .addGap(39, 39, 39)
                            .addComponent(StaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(lblStaffID1)
                            .addGap(40, 40, 40)
                            .addComponent(hourlyRateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(lblStaffName1)
                            .addGap(43, 43, 43)
                            .addComponent(scheduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(lblStaffName2)
                            .addGap(39, 39, 39)
                            .addComponent(positionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(addStaffButton)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(returnButton)
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStaffID)
                        .addComponent(StaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStaffName)
                        .addComponent(StaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStaffID1)
                        .addComponent(hourlyRateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStaffName1)
                        .addComponent(scheduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStaffName2)
                        .addComponent(positionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(addStaffButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffIDActionPerformed

    private void StaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffNameActionPerformed

    private void scheduleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleComboBoxActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.guiStaffElement.setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffButtonActionPerformed
        // TODO add your handling code here:
        byte id = 0;

        try {
            id = Byte.parseByte(this.StaffID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Staff Id should be a number!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        String name = this.StaffName.getText();
        byte rate = Byte.parseByte(this.hourlyRateSpinner.getValue().toString());
        String schedule = this.scheduleComboBox.getSelectedItem().toString();
        String position = this.positionComboBox1.getSelectedItem().toString();
        String timeSchedule = "";

        if (schedule.equals("Afternoon shift (12:00-18:00)")) {
            timeSchedule += "12:00-18:00";
        } else if (schedule.equals("Night shift (18:00-24:00)")) {
            timeSchedule += "18:00-24:00";
        }

        if (!stage4.StaffManager.contains(id)) {
            if (position.equals("Ticket staff")) {
                stage4.StaffManager.addStaff(new stage4.TicketStaff(name, id, rate, timeSchedule));
            } else if (position.equals("Food staff")) {
                stage4.StaffManager.addStaff(new stage4.FoodStaff(name, id, rate, timeSchedule));
            } else {
                System.out.println("Invalid role");
            }
        } else {
            System.out.println("Staff with id " + id + " already exists");
        }
        this.dispose();
        
        this.guiStaffElement.resetRows();
        
        this.guiStaffElement.populateTable();
        
        this.guiStaffElement.setVisible(true);

    }//GEN-LAST:event_addStaffButtonActionPerformed

    private void positionComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_StaffAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StaffID;
    private javax.swing.JTextField StaffName;
    private javax.swing.JToggleButton addStaffButton;
    private javax.swing.JSpinner hourlyRateSpinner;
    private javax.swing.JLabel lblStaffID;
    private javax.swing.JLabel lblStaffID1;
    private javax.swing.JLabel lblStaffName;
    private javax.swing.JLabel lblStaffName1;
    private javax.swing.JLabel lblStaffName2;
    private javax.swing.JComboBox<String> positionComboBox1;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> scheduleComboBox;
    // End of variables declaration//GEN-END:variables
}
