/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


import stage4.FoodRelated.*;

/**
 *
 * @author hmreg
 */
public class GUI_ConcessionElements extends javax.swing.JFrame {

    private ArrayList<Food> menuList;
    
    /**
     * Creates new form GUI_ConcessionElements
     */
    public GUI_ConcessionElements() {
        initComponents();
        
        populateTable();
        
    }

    public void populateTable() {
        DefaultTableModel foodTableModel = (DefaultTableModel) this.ComboTbl.getModel();
        
        this.menuList = MenuManager.getMenuList();
        
        for (Food food : this.menuList) {
            Object[] aRow = new Object[7];
            
            
            byte id = food.getMenuId();
            String name = food.getMenuName();
            byte cost = food.getPrice();
            
            aRow[0] = id;
            aRow[1] = name;
            aRow[2] = cost;
            
            foodTableModel.addRow(aRow);

        }
    }
    
    public void resetRows() {
        DefaultTableModel foodTableModel = (DefaultTableModel) this.ComboTbl.getModel();
        
        foodTableModel.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConcessionTab = new javax.swing.JTabbedPane();
        FoodTab = new javax.swing.JPanel();
        CombosTab = new javax.swing.JTabbedPane();
        CombosPnl = new javax.swing.JPanel();
        Addbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ComboTbl = new javax.swing.JTable();
        RemoveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DisplayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        ComboTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        jScrollPane3.setViewportView(ComboTbl);

        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");

        DisplayBtn.setText("Display Receipe");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CombosPnlLayout = new javax.swing.GroupLayout(CombosPnl);
        CombosPnl.setLayout(CombosPnlLayout);
        CombosPnlLayout.setHorizontalGroup(
            CombosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CombosPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CombosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveBtn)
                    .addComponent(Addbtn)
                    .addComponent(UpdateBtn)
                    .addComponent(DisplayBtn))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        CombosPnlLayout.setVerticalGroup(
            CombosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CombosPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CombosPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        CombosTab.addTab("Combos", CombosPnl);

        javax.swing.GroupLayout FoodTabLayout = new javax.swing.GroupLayout(FoodTab);
        FoodTab.setLayout(FoodTabLayout);
        FoodTabLayout.setHorizontalGroup(
            FoodTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodTabLayout.createSequentialGroup()
                .addComponent(CombosTab, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FoodTabLayout.setVerticalGroup(
            FoodTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CombosTab)
        );

        ConcessionTab.addTab("Concession Stand", FoodTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConcessionTab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConcessionTab)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed

        GUI_AddMenu guiAddMenu = new GUI_AddMenu(this);
        guiAddMenu.setVisible(true);
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed

        new GUI_Receipe().setVisible(true);
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed

        int selectedRow = this.ComboTbl.getSelectedRow();
        
        if (selectedRow != -1) {
            byte id = (byte) (this.ComboTbl.getModel().getValueAt(selectedRow, 0));
            MenuManager.removeMenu(id);
        }
    }//GEN-LAST:event_RemoveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ConcessionElements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JTable ComboTbl;
    private javax.swing.JPanel CombosPnl;
    private javax.swing.JTabbedPane CombosTab;
    private javax.swing.JTabbedPane ConcessionTab;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JPanel FoodTab;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
