package GUI;

import stage4.OrdersAndPayment.*;
import stage4.FoodRelated.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import stage4.Customer;

import java.util.TreeMap;
import java.util.Map;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lccra
 */
public class GUI_OrderFood extends javax.swing.JFrame {

    private DetailFoodBought detail;
    private ArrayList<Food> foodList;
    
    private GUI_MainMenuFood guiMainMenuFood;
    
    /**
     * Creates new form GUI_OrderFoodOne
     */
    public GUI_OrderFood() {
        initComponents();
    }
    
    public GUI_OrderFood(GUI_MainMenuFood guiMainMenuFood) {
        initComponents();
        detail = new DetailFoodBought(); 
        
        this.guiMainMenuFood = guiMainMenuFood;
        
        populateTableAvailableFood();
    }
    
    public void populateTableAvailableFood() {
        
        this.foodList = MenuManager.getMenuList();
        DefaultTableModel foodModel = (DefaultTableModel) this.tblAvailableFood.getModel();
        
        Object[][] foodRows = new Object[foodList.size()][4];
        for (int i = 0; i < foodList.size(); i++) {
            foodRows[i][0] = foodList.get(i).getMenuId();
            foodRows[i][1] = foodList.get(i).getMenuName();
            foodRows[i][2] = foodList.get(i).getPrice();
            
            foodModel.addRow(foodRows[i]);

        }
    }
    
    public void populateTableOrderedFood() {
        TreeMap<Food, Byte> orderedFood = this.detail.getOrderedFood();
        
        DefaultTableModel orderedModel = (DefaultTableModel) this.tblOrderedFood.getModel();
        
        for (Map.Entry<Food, Byte> entry : orderedFood.entrySet()) {
            Object[] aRow = new Object[3];
            
            byte foodId = entry.getKey().getMenuId();
            
            String foodName = entry.getKey().getMenuName();
            byte qty = entry.getValue();
            
            aRow[0] = foodId;
            aRow[1] = foodName;
            aRow[2] = qty;
            
            orderedModel.addRow(aRow);
        }
    }
    
    public void reset() {
        
        spnAddToOrder.setValue(0);
        tblAvailableFood.clearSelection();
    }
    
    public void resetOrderedFoodTable() {
        DefaultTableModel orderedModel = (DefaultTableModel) this.tblOrderedFood.getModel();

        orderedModel.setRowCount(0);
    }

    private short calculateFoodPrice() {
        short total = 0;
        
        for (Food aFood : this.detail.getOrderedFood().keySet()) {
            total += (aFood.getPrice() * this.detail.getOrderedFood().get(aFood));
        }
        
        return total;
    }
    
    public void updateFoodPrice() {
        short price = this.detail.getPaymentAmount();
        
        this.txtFoodCost.setText(String.valueOf(price));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGPaymentType = new javax.swing.ButtonGroup();
        OrderFoodLbl = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        CustomerNametxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableFood = new javax.swing.JTable();
        PaymentTypeLbl = new javax.swing.JLabel();
        CashBtn = new javax.swing.JRadioButton();
        CardBtn = new javax.swing.JRadioButton();
        txtFoodCost = new javax.swing.JTextField();
        btnReturnFoodMain = new javax.swing.JButton();
        spnAddToOrder = new javax.swing.JSpinner();
        btnTotalFoodPrice = new javax.swing.JButton();
        btnOrderFood = new javax.swing.JButton();
        btnAddToOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderedFood = new javax.swing.JTable();
        btnRemoveFromOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderFoodLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        OrderFoodLbl.setText("Order Food/Drink");
        getContentPane().add(OrderFoodLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        lblCustomerName.setText("Order For:");
        getContentPane().add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 40, -1, -1));

        CustomerNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNametxtActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 117, -1));

        tblAvailableFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food ID", "Food", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblAvailableFood);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 400, 220));

        PaymentTypeLbl.setText("Payment Type:");
        getContentPane().add(PaymentTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnGPaymentType.add(CashBtn);
        CashBtn.setSelected(true);
        CashBtn.setText("Cash");
        getContentPane().add(CashBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        btnGPaymentType.add(CardBtn);
        CardBtn.setText("Card");
        getContentPane().add(CardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        txtFoodCost.setEditable(false);
        txtFoodCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodCostActionPerformed(evt);
            }
        });
        getContentPane().add(txtFoodCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 84, -1));

        btnReturnFoodMain.setText("Return");
        btnReturnFoodMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnFoodMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturnFoodMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        spnAddToOrder.setModel(new javax.swing.SpinnerNumberModel(0, 0, 127, 1));
        getContentPane().add(spnAddToOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        btnTotalFoodPrice.setText("Total: ");
        btnTotalFoodPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalFoodPriceActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotalFoodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnOrderFood.setText("Order");
        btnOrderFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderFoodActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrderFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        btnAddToOrder.setText("Add to Order");
        btnAddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        tblOrderedFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food ID", "Food", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(tblOrderedFood);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 270, 310));

        btnRemoveFromOrder.setText("Remove from Order");
        btnRemoveFromOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveFromOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnFoodMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnFoodMainActionPerformed

        this.dispose();
        this.guiMainMenuFood.setVisible(true);
    }//GEN-LAST:event_btnReturnFoodMainActionPerformed

    private void btnTotalFoodPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalFoodPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalFoodPriceActionPerformed

    private void btnOrderFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderFoodActionPerformed

        this.detail.setCustomer(new Customer(this.CustomerNametxt.getText()));

        Enumeration<AbstractButton> buttons = this.btnGPaymentType.getElements();
            
            while (buttons.hasMoreElements()) {
                JRadioButton aButton = (JRadioButton) buttons.nextElement();
                
                if (aButton.isSelected()) {
                    this.detail.setPaymentType(aButton.getText());
                }
            }
        
            
        this.setVisible(false);
            
        new GUI_OrderConfirmation(this.guiMainMenuFood, this, detail).setVisible(true);

    }//GEN-LAST:event_btnOrderFoodActionPerformed

    private void btnAddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToOrderActionPerformed

        byte id = 0;
        int selectedRow = this.tblAvailableFood.getSelectedRow();
        
        if (selectedRow != -1) {
            id = Byte.parseByte(this.tblAvailableFood.getValueAt(selectedRow, 0).toString());
            Food menu = MenuManager.searchMenu(id);

            byte qty = Byte.parseByte(this.spnAddToOrder.getValue().toString());
            
            this.detail.addFood(menu, qty);
            
            this.detail.setPaymentAmount(calculateFoodPrice());
            
            updateFoodPrice();
            
            reset();
            
            resetOrderedFoodTable();            
            populateTableOrderedFood();
            
        }  

    }//GEN-LAST:event_btnAddToOrderActionPerformed

    private void CustomerNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNametxtActionPerformed



    }//GEN-LAST:event_CustomerNametxtActionPerformed

    private void txtFoodCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodCostActionPerformed


    }//GEN-LAST:event_txtFoodCostActionPerformed

    private void btnRemoveFromOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromOrderActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.tblOrderedFood.getSelectedRow();
        
        if (selectedRow != -1) {
            
            byte id = (byte) this.tblOrderedFood.getValueAt(selectedRow, 0);
            
            Food aFood = MenuManager.searchMenu(id);
            
            this.detail.removeFood(aFood); 
            
            this.detail.setPaymentAmount(calculateFoodPrice());
            
            updateFoodPrice();
            
            resetOrderedFoodTable();            
            populateTableOrderedFood();
        }
    }//GEN-LAST:event_btnRemoveFromOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_OrderFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CardBtn;
    private javax.swing.JRadioButton CashBtn;
    private javax.swing.JTextField CustomerNametxt;
    private javax.swing.JLabel OrderFoodLbl;
    private javax.swing.JLabel PaymentTypeLbl;
    private javax.swing.JButton btnAddToOrder;
    private javax.swing.ButtonGroup btnGPaymentType;
    private javax.swing.JButton btnOrderFood;
    private javax.swing.JButton btnRemoveFromOrder;
    private javax.swing.JButton btnReturnFoodMain;
    private javax.swing.JButton btnTotalFoodPrice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JSpinner spnAddToOrder;
    private javax.swing.JTable tblAvailableFood;
    private javax.swing.JTable tblOrderedFood;
    private javax.swing.JTextField txtFoodCost;
    // End of variables declaration//GEN-END:variables
}
