/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


import stage4.FoodRelated.*;

/**
 *
 * @author hmreg
 */
public class GUI_ConcessionElements extends javax.swing.JFrame {

    private ArrayList<Food> menuList;
    private ArrayList<Item> itemList;
    
    private GUI_MainMenuFood guiMainMenuFood;
    
    /**
     * Creates new form GUI_ConcessionElements
     */
    public GUI_ConcessionElements() {
        initComponents();
        
        populateTableFood();
        populateTableItem();
        
    }
    
    public GUI_ConcessionElements(GUI_MainMenuFood guiMainMenuFood) {
        initComponents();
        
        this.guiMainMenuFood = guiMainMenuFood;
        
        populateTableFood();
        populateTableItem();
        
    }

    public void populateTableFood() {
        DefaultTableModel foodTableModel = (DefaultTableModel) this.ComboTbl.getModel();
        
        this.menuList = MenuManager.getMenuList();
        
        
        for (Food food : this.menuList) {
            Object[] aRow = new Object[3];
            
            
            byte id = food.getMenuId();
            String name = food.getMenuName();
            byte cost = food.getPrice();
            
            aRow[0] = id;
            aRow[1] = name;
            aRow[2] = cost;
            
            foodTableModel.addRow(aRow);

        }
    }
    
    public void resetRowsFood() {
        DefaultTableModel foodTableModel = (DefaultTableModel) this.ComboTbl.getModel();
        
        foodTableModel.setRowCount(0);
    }
    
    public void populateTableItem() {
        DefaultTableModel itemTableModel = (DefaultTableModel) this.ItemTbl.getModel();
        
        this.itemList = Inventory.getItemList();
        
        for (Item item : this.itemList) {
            Object[] aRow = new Object[4];
            
            byte id = item.getItemId();
            String name = item.getItemName();
            short quantity = item.getQuantity();
            short buyingCost = item.getBuyingCost();
            
            aRow[0] = id;
            aRow[1] = name;
            aRow[2] = quantity;
            aRow[3] = buyingCost;
            
            itemTableModel.addRow(aRow);
            
        }
    }
    
    public void resetRowsItem() {
        DefaultTableModel itemTableModel = (DefaultTableModel) this.ItemTbl.getModel();
        
        itemTableModel.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngredientsTab = new javax.swing.JTabbedPane();
        CombosPnl = new javax.swing.JPanel();
        Addbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ComboTbl = new javax.swing.JTable();
        RemoveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DisplayBtn = new javax.swing.JButton();
        ReturnBtnCombos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemTbl = new javax.swing.JTable();
        AddItemBtn = new javax.swing.JButton();
        RemoveItemBtn = new javax.swing.JButton();
        UpdateItemBtn = new javax.swing.JButton();
        ReturnBtnIngredients = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        ComboTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        jScrollPane3.setViewportView(ComboTbl);

        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DisplayBtn.setText("Display Receipe");
        DisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBtnActionPerformed(evt);
            }
        });

        ReturnBtnCombos.setText("Return");
        ReturnBtnCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnCombosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CombosPnlLayout = new javax.swing.GroupLayout(CombosPnl);
        CombosPnl.setLayout(CombosPnlLayout);
        CombosPnlLayout.setHorizontalGroup(
            CombosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CombosPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CombosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveBtn)
                    .addComponent(Addbtn)
                    .addComponent(UpdateBtn)
                    .addComponent(DisplayBtn)
                    .addComponent(ReturnBtnCombos))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        CombosPnlLayout.setVerticalGroup(
            CombosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CombosPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayBtn)
                .addGap(78, 78, 78)
                .addComponent(ReturnBtnCombos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CombosPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        IngredientsTab.addTab("Combos", CombosPnl);

        ItemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ingredients", "Quantity", "Buying cost"
            }
        ));
        jScrollPane1.setViewportView(ItemTbl);

        AddItemBtn.setText("Add");
        AddItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemBtnActionPerformed(evt);
            }
        });

        RemoveItemBtn.setText("Remove");
        RemoveItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItemBtnActionPerformed(evt);
            }
        });

        UpdateItemBtn.setText("Update");
        UpdateItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateItemBtnActionPerformed(evt);
            }
        });

        ReturnBtnIngredients.setText("Return");
        ReturnBtnIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnIngredientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddItemBtn)
                    .addComponent(RemoveItemBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ReturnBtnIngredients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateItemBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(AddItemBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveItemBtn)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateItemBtn)
                        .addGap(92, 92, 92)
                        .addComponent(ReturnBtnIngredients)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        IngredientsTab.addTab("Ingredients", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(IngredientsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IngredientsTab)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed

        GUI_AddMenu guiAddMenu = new GUI_AddMenu(this);
        guiAddMenu.setVisible(true);
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void DisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBtnActionPerformed

        int selectedRow = this.ComboTbl.getSelectedRow();
        
        if (selectedRow != -1) {
            byte id = (byte) this.ComboTbl.getModel().getValueAt(selectedRow, 0);
            Food selectedFood = MenuManager.searchMenu(id);
            
            GUI_Recipe guiRecipe = new GUI_Recipe(this, selectedFood);
            guiRecipe.setVisible(true);
        }
    }//GEN-LAST:event_DisplayBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed

        int selectedRow = this.ComboTbl.getSelectedRow();
        
        if (selectedRow != -1) {
            byte id = (byte) (this.ComboTbl.getModel().getValueAt(selectedRow, 0));
            MenuManager.removeMenu(id);
            
            resetRowsFood();
            populateTableFood();
        }
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed

    int selectedRow = this.ComboTbl.getSelectedRow();
    
    if (selectedRow != -1) {
        GUI_UpdateMenu guiUpdateMenu = new GUI_UpdateMenu(this, selectedRow);
        guiUpdateMenu.setVisible(true);
    }
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void ReturnBtnCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnCombosActionPerformed
        this.dispose();
        this.guiMainMenuFood.setVisible(true);
    }//GEN-LAST:event_ReturnBtnCombosActionPerformed

    private void AddItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemBtnActionPerformed

        GUI_ItemAdd guiItemAdd = new GUI_ItemAdd(this);
        guiItemAdd.setVisible(true);
        
    }//GEN-LAST:event_AddItemBtnActionPerformed

    private void RemoveItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveItemBtnActionPerformed

        int selectedRow = this.ItemTbl.getSelectedRow();
        
        if(selectedRow != -1) {
            byte id = (byte) (this.ItemTbl.getModel().getValueAt(selectedRow, 0));
            Inventory.removeItem(id);
            
            resetRowsItem();
            populateTableItem();
        }
    }//GEN-LAST:event_RemoveItemBtnActionPerformed

    private void UpdateItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateItemBtnActionPerformed

        int selectedRow = this.ItemTbl.getSelectedRow();
        
        if(selectedRow != -1) {
            GUI_ItemUpdate guiItemUpdate = new GUI_ItemUpdate(this, selectedRow);
            guiItemUpdate.setVisible(true);
        }
    }//GEN-LAST:event_UpdateItemBtnActionPerformed

    private void ReturnBtnIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnIngredientsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.guiMainMenuFood.setVisible(true);
    }//GEN-LAST:event_ReturnBtnIngredientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ConcessionElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ConcessionElements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemBtn;
    private javax.swing.JButton Addbtn;
    private javax.swing.JTable ComboTbl;
    private javax.swing.JPanel CombosPnl;
    private javax.swing.JButton DisplayBtn;
    private javax.swing.JTabbedPane IngredientsTab;
    private javax.swing.JTable ItemTbl;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton RemoveItemBtn;
    private javax.swing.JButton ReturnBtnCombos;
    private javax.swing.JButton ReturnBtnIngredients;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateItemBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
