/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author ivans
 */
public class GUI_DummyMenu extends javax.swing.JFrame {

    private GUI_LogIn gui_login;
    
    /**
     * Creates new form GUI_DummyMenu
     */
    public GUI_DummyMenu(GUI_LogIn gui_login) {
        initComponents();
        this.gui_login = gui_login;
    }
    
    public GUI_DummyMenu() {
        initComponents(); 
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffID = new javax.swing.JTextField();
        StaffName = new javax.swing.JTextField();
        lblStaffID = new javax.swing.JLabel();
        lblStaffName = new javax.swing.JLabel();
        lblStaffID1 = new javax.swing.JLabel();
        lblStaffName1 = new javax.swing.JLabel();
        hourlyRateSpinner = new javax.swing.JSpinner();
        scheduleComboBox = new javax.swing.JComboBox<>();
        lblStaffName2 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        addStaffButton = new javax.swing.JToggleButton();
        positionComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffIDActionPerformed(evt);
            }
        });
        getContentPane().add(StaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 46, 200, -1));

        StaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffNameActionPerformed(evt);
            }
        });
        getContentPane().add(StaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, -1));

        lblStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffID.setText("Staff ID:");
        getContentPane().add(lblStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 46, -1, -1));

        lblStaffName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName.setText("Staff Name:");
        getContentPane().add(lblStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        lblStaffID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffID1.setText("Hourly rate");
        getContentPane().add(lblStaffID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        lblStaffName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName1.setText("Schedule");
        getContentPane().add(lblStaffName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        hourlyRateSpinner.setModel(new javax.swing.SpinnerNumberModel(12, 12, 25, 1));
        hourlyRateSpinner.setAutoscrolls(true);
        hourlyRateSpinner.setDoubleBuffered(true);
        getContentPane().add(hourlyRateSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, -1));

        scheduleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afternoon shift (12:00-18:00)", "Night shift (18:00-24:00)" }));
        scheduleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(scheduleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 200, -1));

        lblStaffName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName2.setText("Position");
        getContentPane().add(lblStaffName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 17, -1, -1));

        addStaffButton.setText("Add staff");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addStaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        positionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ticket staff", "Food staff" }));
        positionComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(positionComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_StaffIDActionPerformed

    private void StaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffNameActionPerformed

    private void scheduleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleComboBoxActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffButtonActionPerformed
        // TODO add your handling code here:
        byte id = Byte.parseByte(this.StaffID.getText());
        String name = this.StaffName.getText();
        byte rate = Byte.parseByte(this.hourlyRateSpinner.getValue().toString());
        String schedule = this.scheduleComboBox.getSelectedItem().toString();
        String position = this.positionComboBox1.getSelectedItem().toString();
        
        String timeSchedule = "";
        
        if (schedule.equals("Afternoon shift (12:00-18:00)")) {
            timeSchedule += "12:00-18:00";
        } else if (schedule.equals("Night shift (18:00-24:00)")) {
            timeSchedule += "18:00-24:00";
        }
        
        if (!stage4.StaffManager.contains(id)) {
            if (position.equals("Ticket staff")) {
                stage4.StaffManager.addStaff(new stage4.TicketStaff(name, id, rate, timeSchedule));
            } else if (position.equals("Food staff")) {
                stage4.StaffManager.addStaff(new stage4.FoodStaff(name, id, rate, timeSchedule));
            } else {
                System.out.println("Invalid role");
            }
        } else {
            System.out.println("Staff with id " + id + " already exists");
        }
        this.dispose();
        this.gui_login.setVisible(true);
        
    }//GEN-LAST:event_addStaffButtonActionPerformed

    private void positionComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DummyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DummyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DummyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DummyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_DummyMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StaffID;
    private javax.swing.JTextField StaffName;
    private javax.swing.JToggleButton addStaffButton;
    private javax.swing.JSpinner hourlyRateSpinner;
    private javax.swing.JLabel lblStaffID;
    private javax.swing.JLabel lblStaffID1;
    private javax.swing.JLabel lblStaffName;
    private javax.swing.JLabel lblStaffName1;
    private javax.swing.JLabel lblStaffName2;
    private javax.swing.JComboBox<String> positionComboBox1;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> scheduleComboBox;
    // End of variables declaration//GEN-END:variables
}
