package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/** 
 *
 * @author lccra
 */
public class GUI_OrderMovieTicket extends javax.swing.JFrame {

    /**
     * Creates new form GUI_OrderMovieTicket
     */
    public GUI_OrderMovieTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGPayment = new javax.swing.ButtonGroup();
        lblCustomerNameTicket = new javax.swing.JLabel();
        lblPaymentTypeTicket = new javax.swing.JLabel();
        txtCustomerNameTicket = new javax.swing.JTextField();
        RbtnCash = new javax.swing.JRadioButton();
        RbtnCredit = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Movie Ticket");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerNameTicket.setText("Order For:");
        getContentPane().add(lblCustomerNameTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, -1, -1));

        lblPaymentTypeTicket.setText("Payment Type:");
        getContentPane().add(lblPaymentTypeTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 59, -1, -1));

        txtCustomerNameTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameTicketActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustomerNameTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 71, -1));

        btnGPayment.add(RbtnCash);
        RbtnCash.setSelected(true);
        RbtnCash.setText("Cash");
        RbtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnCashActionPerformed(evt);
            }
        });
        getContentPane().add(RbtnCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        btnGPayment.add(RbtnCredit);
        RbtnCredit.setText("Credit Card");
        getContentPane().add(RbtnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title ", "Genre", "Duration"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, 380));

        setSize(new java.awt.Dimension(414, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNameTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameTicketActionPerformed

    private void RbtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnCashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderMovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderMovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderMovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_OrderMovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_OrderMovieTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtnCash;
    private javax.swing.JRadioButton RbtnCredit;
    private javax.swing.ButtonGroup btnGPayment;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCustomerNameTicket;
    private javax.swing.JLabel lblPaymentTypeTicket;
    private javax.swing.JTextField txtCustomerNameTicket;
    // End of variables declaration//GEN-END:variables
}
