package GUI;

import javax.swing.JOptionPane;
import stage4.TicketRelated.ScreenManager;
import stage4.TicketRelated.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lccra
 */
public class GUI_ScreenUpdate extends javax.swing.JFrame {

    private GUI_MovieElements guiMovieElements;
    private int selectedRow;
    
    /**
     * Creates new form GUI_ScreenUpdate
     */
    public GUI_ScreenUpdate() {
        initComponents();
    }
    
    public GUI_ScreenUpdate(GUI_MovieElements guiMovieElements, int selectedRow) {
        
    initComponents();
    this.selectedRow = selectedRow;
    this.guiMovieElements = guiMovieElements;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnMovieElements = new javax.swing.JButton();
        txtUpdateScreenID = new javax.swing.JTextField();
        lblScreenID = new javax.swing.JLabel();
        lblScreenType = new javax.swing.JLabel();
        btnUpdateScreen = new javax.swing.JButton();
        screenTypeBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReturnMovieElements.setText("Return");
        btnReturnMovieElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMovieElementsActionPerformed(evt);
            }
        });

        lblScreenID.setText("Screen ID:");

        lblScreenType.setText("Screen Type:");

        btnUpdateScreen.setText("Update");
        btnUpdateScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateScreenActionPerformed(evt);
            }
        });

        screenTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "imax" }));
        screenTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenTypeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReturnMovieElements)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScreenType)
                    .addComponent(lblScreenID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpdateScreenID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(screenTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnUpdateScreen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReturnMovieElements)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateScreenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScreenID))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScreenType)
                    .addComponent(screenTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnUpdateScreen)
                .addGap(30, 30, 30))
        );

        setSize(new java.awt.Dimension(414, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMovieElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMovieElementsActionPerformed

        this.guiMovieElements.setVisible(true);

    }//GEN-LAST:event_btnReturnMovieElementsActionPerformed

    private void btnUpdateScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateScreenActionPerformed

        byte id = 0;
        
        try {
            id = Byte.parseByte(this.txtUpdateScreenID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Screen ID must be a number!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        String screenType = this.screenTypeBox.getSelectedItem().toString();
        
        ScreenManager.updateScreen((byte) this.selectedRow, new Screen(id, screenType));

        this.dispose();
        
        this.guiMovieElements.resetRowsScreen();
        
        this.guiMovieElements.populateTableScreen();
        
        this.guiMovieElements.setVisible(true);

    }//GEN-LAST:event_btnUpdateScreenActionPerformed

    private void screenTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screenTypeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ScreenUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ScreenUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ScreenUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ScreenUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ScreenUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnMovieElements;
    private javax.swing.JButton btnUpdateScreen;
    private javax.swing.JLabel lblScreenID;
    private javax.swing.JLabel lblScreenType;
    private javax.swing.JComboBox<String> screenTypeBox;
    private javax.swing.JTextField txtUpdateScreenID;
    // End of variables declaration//GEN-END:variables
}
