/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stage4.*;

/**
 *
 * @author ivans
 */
public class GUI_StaffElements extends javax.swing.JFrame {

    private GUI_StaffElements guiStaffElement;
    
    private GUI_MainMenuTicket guiMainMenuTicket;
    private GUI_MainMenuFood guiMainMenuFood;
    private ArrayList<Staff> staffs;
    
    /**
     * Creates new form GUI_StaffElements
     */
    public GUI_StaffElements() {
        initComponents();
        
        this.guiStaffElement = this;
        
        populateTable();
    }

     public GUI_StaffElements(GUI_MainMenuFood guiMainMenuFood) {
        initComponents();
        this.guiMainMenuFood = guiMainMenuFood;
        
        this.guiStaffElement = this;
        
        populateTable();
    }
    
    public GUI_StaffElements(GUI_MainMenuTicket guiMainMenuTicket) {
        initComponents();
        this.guiMainMenuTicket = guiMainMenuTicket;
        
        this.guiStaffElement = this;
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel staffTableModel = (DefaultTableModel) this.tableStaff.getModel();
         
        this.staffs = StaffManager.getStaffs();
        
        for (Staff staff : this.staffs) {
            Object[] aRow = new Object[5];
            
            byte id = staff.getEmployeeId();
            String name = staff.getEmployeeName();
            byte hourlyRate = staff.getHourlyRate();
            String schedule = staff.getSchedule();
            String position = staff.getRole();
        
            aRow[0] = id;
            aRow[1] = name;
            aRow[2] = hourlyRate;
            aRow[3] = schedule;
            aRow[4] = position;
            
            staffTableModel.addRow(aRow);
        }
    }
    
    public void resetRows() {
        DefaultTableModel staffTableModel = (DefaultTableModel) this.tableStaff.getModel();
        
        staffTableModel.setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableStaff = new javax.swing.JTable();
        addStaffButton = new javax.swing.JButton();
        removeStaffButton = new javax.swing.JButton();
        updateStaffButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Hourly rate", "Schedule", "Position"
            }
        ));
        jScrollPane1.setViewportView(tableStaff);

        addStaffButton.setText("Add");
        addStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffButtonActionPerformed(evt);
            }
        });

        removeStaffButton.setText("Remove");
        removeStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStaffButtonActionPerformed(evt);
            }
        });

        updateStaffButton.setText("Update");
        updateStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStaffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStaffButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeStaffButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateStaffButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(addStaffButton)
                .addGap(18, 18, 18)
                .addComponent(removeStaffButton)
                .addGap(27, 27, 27)
                .addComponent(updateStaffButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffButtonActionPerformed
        // TODO add your handling code here:
        GUI_StaffAdd guiStaffAdd = new GUI_StaffAdd(this.guiStaffElement);
        
        guiStaffAdd.setVisible(true);
        
        
    }//GEN-LAST:event_addStaffButtonActionPerformed

    private void removeStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStaffButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.tableStaff.getSelectedRow();
        
        if (selectedRow != -1) {
            StaffManager.removeStaff((byte) selectedRow);
        }
    }//GEN-LAST:event_removeStaffButtonActionPerformed

    private void updateStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = this.tableStaff.getSelectedRow();
        
        if (selectedRow != -1) {
            GUI_StaffUpdate guiStaffUpdate = new GUI_StaffUpdate(this.guiStaffElement, selectedRow);
            guiStaffUpdate.setVisible(true);
        }
    }//GEN-LAST:event_updateStaffButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_StaffElements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_StaffElements().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeStaffButton;
    private javax.swing.JTable tableStaff;
    private javax.swing.JButton updateStaffButton;
    // End of variables declaration//GEN-END:variables
}
