package GUI;


import GUI.GUI_AnalyticsMenu;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;
import stage4.util.Path;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ivans
 */
public class GUI_ReportFoodSales extends javax.swing.JFrame {

    private GUI_AnalyticsMenu guiAnalyticsMenu;

    
    /**
     * Creates new form GUI_ReportFoodSales
     */
    public GUI_ReportFoodSales() {
        initComponents();
    }

    public GUI_ReportFoodSales(GUI_AnalyticsMenu guiAnalyticsMenu, LocalDate timeStart, LocalDate timeEnd) {
        initComponents();
        
        this.guiAnalyticsMenu = guiAnalyticsMenu;
        
        DefaultTableModel foodReportModel = (DefaultTableModel) this.tableFoodSales.getModel();
        
        try (BufferedReader reader = new BufferedReader(new FileReader(Path.FOOD_SALES_REPORT_PATH))) {

            String line;

            while ((line = reader.readLine()) != null) {
                
                
                String orderInfo = line.split(";")[0];
                String orderList = line.split(";")[1];

                String paymentId = orderInfo.split(",")[0];
                LocalDateTime time = LocalDateTime.parse(orderInfo.split(",")[1]);
                String totalPrice = orderInfo.split(",")[2];

                String[] orderArray = orderList.split(",");

                if (timeStart != null && timeEnd != null && time.isAfter(timeStart.atStartOfDay()) && time.isBefore(timeEnd.atStartOfDay())) {

                    Object[] aRowHead = new Object[5];
                    
                    aRowHead[0] = paymentId;
                    aRowHead[1] = time;
                    aRowHead[2] = orderArray[0];
                    aRowHead[3] = orderArray[1];
                    aRowHead[4] = "$" + orderArray[2];
                    
                    foodReportModel.addRow(aRowHead);
                    
                    if (orderArray.length > 3) {
                        for (int i=3; i<orderArray.length; i+=3) {

                            Object[] aRow = new Object[5];
                            
                            aRow[0] = "";
                            aRow[1] = "";
                            aRow[2] = orderArray[i];
                            aRow[3] = orderArray[i+1];
                            aRow[4] = "$" + orderArray[i+2];
                            
                            foodReportModel.addRow(aRow);
                            
                        }
                    }
                    
                    Object[] aRowFoot = new Object[5];
                    
                    aRowFoot[0] = "";
                    aRowFoot[1] = "";
                    aRowFoot[2] = "";
                    aRowFoot[3] = "Total price";
                    aRowFoot[4] = "$" + totalPrice;
                    
                    foodReportModel.addRow(aRowFoot);
                }
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFoodSales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableFoodSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Timestamp", "Food name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(tableFoodSales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportFoodSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportFoodSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportFoodSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ReportFoodSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ReportFoodSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFoodSales;
    // End of variables declaration//GEN-END:variables
}
