package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.table.DefaultTableModel;
import stage4.FoodRelated.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ivans
 */
public class GUI_RecipeAdd extends javax.swing.JFrame {

    private GUI_Recipe guiRecipe;
    private Food food;
    
    /**
     * Creates new form GUI_RecipeAdd
     */
    public GUI_RecipeAdd() {
        initComponents();
    }
    
    public GUI_RecipeAdd(GUI_Recipe guiRecipe, Food food) {
        initComponents();

        this.guiRecipe = guiRecipe;
        this.food = food;
        
        populateItemRecipeTable();
    }

    public void populateItemRecipeTable() {

        DefaultTableModel itemRecipeTable = (DefaultTableModel) this.tableItem.getModel();
        
        ArrayList<Item> itemList = Inventory.getItemList();
                
        for (Item item : itemList) {
            Object[] aRow = new Object[2];
            
            byte id = item.getItemId();
            String name = item.getItemName();
            
            aRow[0] = id;
            aRow[1] = name;
            
            itemRecipeTable.addRow(aRow);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItem = new javax.swing.JTable();
        addRecipeButton = new javax.swing.JButton();
        spinnerItemQty = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item name"
            }
        ));
        jScrollPane1.setViewportView(tableItem);

        addRecipeButton.setText("Add");
        addRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButtonActionPerformed(evt);
            }
        });

        spinnerItemQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, 127, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRecipeButton)
                    .addComponent(spinnerItemQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(spinnerItemQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addRecipeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = this.tableItem.getSelectedRow();
        
        if (selectedRow != -1) {
            byte id = (byte) this.tableItem.getModel().getValueAt(selectedRow, 0);
            String name = String.valueOf(this.tableItem.getModel().getValueAt(selectedRow, 1));
            
            int qty = (int) this.spinnerItemQty.getValue();
            
            Item anItem = Inventory.getItem(id);
            
            if (this.food.getRecipe().containsKey(anItem)) {
                JOptionPane.showMessageDialog(null, "Item already exist as part of the recipe!");
            } else {
                this.food.addRecipe(anItem, (byte) qty);
            }
            
            this.dispose();
            
            this.guiRecipe.resetRowsRecipe();
            
            this.guiRecipe.populateTableRecipe();
            
            this.guiRecipe.setVisible(true);
        }
    }//GEN-LAST:event_addRecipeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RecipeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RecipeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RecipeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RecipeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_RecipeAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecipeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerItemQty;
    private javax.swing.JTable tableItem;
    // End of variables declaration//GEN-END:variables
}
