/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import stage4.FoodRelated.*;

/**
 *
 * @author hmreg
 */
public class GUI_UpdateMenu extends javax.swing.JFrame {
    private int selectedRow;
    private GUI_ConcessionElements guiConcessionElements;
    
    
    /**
     * Creates new form GUI_UpdateMenu
     */
    public GUI_UpdateMenu() {
        initComponents();
    }

    public GUI_UpdateMenu(GUI_ConcessionElements guiConcessionElements, int selectedRow) {
       initComponents();
       this.selectedRow = selectedRow;
       this.guiConcessionElements = guiConcessionElements;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateIDLbl = new javax.swing.JLabel();
        UpdateMenuItemLbl = new javax.swing.JLabel();
        UpdateMenuCostLbl = new javax.swing.JLabel();
        UpdateIDTxt = new javax.swing.JTextField();
        UpdateItemTxt = new javax.swing.JTextField();
        UpdateCostTxt = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        ReturnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        UpdateIDLbl.setText("Update Menu ID:");

        UpdateMenuItemLbl.setText("Update Menu Item:");

        UpdateMenuCostLbl.setText("Update Menu Price:");

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        ReturnBtn.setText("Return");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateMenuCostLbl)
                        .addGap(44, 44, 44)
                        .addComponent(UpdateCostTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateMenuItemLbl)
                        .addGap(45, 45, 45)
                        .addComponent(UpdateItemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateIDLbl)
                        .addGap(57, 57, 57)
                        .addComponent(UpdateIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReturnBtn)
                    .addComponent(UpdateBtn))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateIDLbl)
                    .addComponent(UpdateIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateMenuItemLbl)
                    .addComponent(UpdateItemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateMenuCostLbl)
                    .addComponent(UpdateCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(UpdateBtn)
                .addGap(18, 18, 18)
                .addComponent(ReturnBtn)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed

        byte id = 0;
        
        try {
           id = Byte.parseByte(this.UpdateIDTxt.getText());
           
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Menu ID should be a number.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        String name = this.UpdateIDTxt.getText();
        
        byte cost = 0;
        
        try {
            cost = Byte.parseByte(this.UpdateCostTxt.getText());
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Menu Price should be a number.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        MenuManager.updateMenu((byte) this.selectedRow, new Food(id, name, cost));
        
        this.dispose();
        
        this.guiConcessionElements.resetRowsFood();
        
        this.guiConcessionElements.populateTableFood();
        
        this.guiConcessionElements.setVisible(true);
        
        
       
        
        
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_UpdateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_UpdateMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField UpdateCostTxt;
    private javax.swing.JLabel UpdateIDLbl;
    private javax.swing.JTextField UpdateIDTxt;
    private javax.swing.JTextField UpdateItemTxt;
    private javax.swing.JLabel UpdateMenuCostLbl;
    private javax.swing.JLabel UpdateMenuItemLbl;
    // End of variables declaration//GEN-END:variables
}
