package GUI;

import javax.swing.JOptionPane;
import stage4.TicketRelated.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lccra
 */
public class GUI_MovieUpdate extends javax.swing.JFrame {

    private GUI_MovieElements guiMovieElements;
    private int selectedRow;
    
    /**
     * Creates new form GUI_MovieUpdate
     */
    public GUI_MovieUpdate() {
        initComponents();
    }
    
    public GUI_MovieUpdate(GUI_MovieElements guiMovieElements, int selectedRow) {
        
    initComponents();
    this.selectedRow = selectedRow;
    this.guiMovieElements = guiMovieElements;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnMovieElements = new javax.swing.JButton();
        txtUpdateMovieTitle = new javax.swing.JTextField();
        txtUpdateMovieGenre = new javax.swing.JTextField();
        txtUpdateMovieDuration = new javax.swing.JTextField();
        lblUpdateMovieTitle = new javax.swing.JLabel();
        lblUpdateMovieGenre = new javax.swing.JLabel();
        lblUpdateMovieDuration = new javax.swing.JLabel();
        btnUpdateMovie = new javax.swing.JButton();
        lblUpdateMovieID = new javax.swing.JLabel();
        txtUpdateMovieID = new javax.swing.JTextField();

        btnReturnMovieElements.setText("Return");
        btnReturnMovieElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMovieElementsActionPerformed(evt);
            }
        });

        txtUpdateMovieTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateMovieTitleActionPerformed(evt);
            }
        });

        lblUpdateMovieTitle.setText("Movie Title:");

        lblUpdateMovieGenre.setText("Movie Genre:");

        lblUpdateMovieDuration.setText("Movie Duration:");

        btnUpdateMovie.setText("Update");
        btnUpdateMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMovieActionPerformed(evt);
            }
        });

        lblUpdateMovieID.setText("Movie ID:");

        txtUpdateMovieID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateMovieIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturnMovieElements)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUpdateMovieTitle)
                            .addComponent(lblUpdateMovieGenre)
                            .addComponent(lblUpdateMovieDuration)
                            .addComponent(lblUpdateMovieID))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpdateMovieDuration)
                            .addComponent(txtUpdateMovieGenre)
                            .addComponent(txtUpdateMovieTitle)
                            .addComponent(txtUpdateMovieID, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addGap(0, 66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnUpdateMovie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReturnMovieElements)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUpdateMovieID)
                    .addComponent(txtUpdateMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateMovieTitle)
                            .addComponent(txtUpdateMovieTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblUpdateMovieGenre))
                    .addComponent(txtUpdateMovieGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUpdateMovieDuration)
                    .addComponent(txtUpdateMovieDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnUpdateMovie)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(414, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpdateMovieTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateMovieTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateMovieTitleActionPerformed

    private void btnReturnMovieElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMovieElementsActionPerformed
        this.dispose();
        this.guiMovieElements.setVisible(true);

    }//GEN-LAST:event_btnReturnMovieElementsActionPerformed

    private void btnUpdateMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMovieActionPerformed

        byte id = 0;
        
        try {
            id = Byte.parseByte(this.txtUpdateMovieID.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Screen ID must be a number!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        String title = this.txtUpdateMovieTitle.getText();
        String genre = this.txtUpdateMovieGenre.getText();
        short duration = Short.parseShort(this.txtUpdateMovieDuration.getText());
        
        
        MovieManager.updateMovie((byte) this.selectedRow, new Movie(id, title, genre, duration));

        this.dispose();
        
        this.guiMovieElements.resetRowsMovies();
        
        this.guiMovieElements.populateTableMovies();
        
        this.guiMovieElements.setVisible(true);


    }//GEN-LAST:event_btnUpdateMovieActionPerformed

    private void txtUpdateMovieIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateMovieIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateMovieIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MovieUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MovieUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MovieUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MovieUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MovieUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnMovieElements;
    private javax.swing.JButton btnUpdateMovie;
    private javax.swing.JLabel lblUpdateMovieDuration;
    private javax.swing.JLabel lblUpdateMovieGenre;
    private javax.swing.JLabel lblUpdateMovieID;
    private javax.swing.JLabel lblUpdateMovieTitle;
    private javax.swing.JTextField txtUpdateMovieDuration;
    private javax.swing.JTextField txtUpdateMovieGenre;
    private javax.swing.JTextField txtUpdateMovieID;
    private javax.swing.JTextField txtUpdateMovieTitle;
    // End of variables declaration//GEN-END:variables
}
