package GUI;

//import javax.swing.JOptionPane;
//import stage4.TicketRelated.ShowtimeManager;
//import stage4.TicketRelated.*;
//import java.time.LocalTime;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lccra
 */
public class GUI_ShowtimeAdd extends javax.swing.JFrame {

    private GUI_MovieElements guiMovieElements;
    
//    private LocalTime startTime;
//    
//    private LocalTime endTime;

    
    /**
     * Creates new form GUI_ShowtimeAdd
     */
    public GUI_ShowtimeAdd() {
        initComponents();
    }
    
    public GUI_ShowtimeAdd(GUI_MovieElements guiMovieElements) {
        initComponents();
        this.guiMovieElements = guiMovieElements;


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtAddShowtimeID = new javax.swing.JTextField();
        txtAddShowtimeTitle = new javax.swing.JTextField();
        txtAddShowtimeStartTime = new javax.swing.JTextField();
        txtAddShowtimeEndTime = new javax.swing.JTextField();
        lblShowtimeID = new javax.swing.JLabel();
        lblMovieTitle = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        btnAddShowtime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblShowtimeID.setText("Showtime ID:");

        lblMovieTitle.setText("Movie Title:");

        lblStartTime.setText("Start Time: ");

        lblEndTime.setText("End Time:");

        btnAddShowtime.setText("Add");
        btnAddShowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddShowtimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShowtimeID)
                            .addComponent(lblMovieTitle)
                            .addComponent(lblStartTime)
                            .addComponent(lblEndTime))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddShowtimeID, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtAddShowtimeStartTime)
                            .addComponent(txtAddShowtimeEndTime)
                            .addComponent(txtAddShowtimeTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnAddShowtime)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddShowtimeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowtimeID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddShowtimeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovieTitle))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddShowtimeStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddShowtimeEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndTime))
                .addGap(29, 29, 29)
                .addComponent(btnAddShowtime)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(434, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new GUI_MovieElements().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddShowtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddShowtimeActionPerformed

//        byte id = 0;
//        
//        try {
//            id = Byte.parseByte(this.txtAddShowtimeID.getText());
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Screen ID must be a number!", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
//        
//        String title = this.txtAddShowtimeTitle.getText();
//        LocalTime startTime = this.txtAddShowtimeStartTime.getText();
//        LocalTime endTime = this.txtAddShowtimeEndTime.getText();
//        
//        if(!ShowtimeManager.contains(id)) {
//            ShowtimeManager.addShowtime(new Showtime(id, title, startTime, endTime));
//        }
//
//        this.dispose();
//        
//        this.guiMovieElements.resetRows();
//        
//        this.guiMovieElements.populateTable();
//        
//        this.guiMovieElements.setVisible(true);

    }//GEN-LAST:event_btnAddShowtimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowtimeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowtimeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowtimeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowtimeAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ShowtimeAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddShowtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblShowtimeID;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JTextField txtAddShowtimeEndTime;
    private javax.swing.JTextField txtAddShowtimeID;
    private javax.swing.JTextField txtAddShowtimeStartTime;
    private javax.swing.JTextField txtAddShowtimeTitle;
    // End of variables declaration//GEN-END:variables
}
