
package GUI;

/**
 *
 * @author lccra
 */
public class GUI_LogIn extends javax.swing.JFrame {
    
    /**
     * Creates new form GUI_LogIn
     */
    public GUI_LogIn() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffID = new javax.swing.JTextField();
        StaffName = new javax.swing.JTextField();
        LogIn = new javax.swing.JLabel();
        lblStaffID = new javax.swing.JLabel();
        lblStaffName = new javax.swing.JLabel();
        btbLoginEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffIDActionPerformed(evt);
            }
        });

        StaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffNameActionPerformed(evt);
            }
        });

        LogIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogIn.setText("Staff LogIn: ");

        lblStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffID.setText("Staff ID:");

        lblStaffName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStaffName.setText("Name:");

        btbLoginEnter.setText("Enter");
        btbLoginEnter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btbLoginEnterStateChanged(evt);
            }
        });
        btbLoginEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLoginEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(LogIn)
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStaffID)
                    .addComponent(lblStaffName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btbLoginEnter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(StaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LogIn)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffID))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btbLoginEnter)
                .addGap(31, 31, 31))
        );

        setSize(new java.awt.Dimension(414, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffIDActionPerformed
        // TODO add your handling code h ere:
        
    }//GEN-LAST:event_StaffIDActionPerformed

    private void StaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffNameActionPerformed

    private void btbLoginEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLoginEnterActionPerformed
        // TODO add your handling code here:
        byte id = Byte.parseByte(this.StaffID.getText());
        String name = this.StaffName.getText();
        
        if (id > 0 && !name.isBlank()) {
            System.out.println("id: " + id);
            System.out.println("name: " + name);
        }
        
    }//GEN-LAST:event_btbLoginEnterActionPerformed

    private void btbLoginEnterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btbLoginEnterStateChanged
        
    }//GEN-LAST:event_btbLoginEnterStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_LogIn gui_login = new GUI_LogIn();

                if (!stage4.StaffManager.hasStaffs()) {
                    GUI_DummyMenu gui_dummy = new GUI_DummyMenu(gui_login);
                    gui_dummy.setVisible(true);
                } else {
                    gui_login.setVisible(true);
                }
                
                
                
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogIn;
    private javax.swing.JTextField StaffID;
    private javax.swing.JTextField StaffName;
    private javax.swing.JButton btbLoginEnter;
    private javax.swing.JLabel lblStaffID;
    private javax.swing.JLabel lblStaffName;
    // End of variables declaration//GEN-END:variables

}
