/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author lccra
 */
public class GUI_MainMenuFood extends javax.swing.JFrame {
    private GUI_LogIn guiLogin;
    
    /**
     * Creates new form GUI_MainMenu
     */
    public GUI_MainMenuFood() {
        initComponents();
    }
    
    public GUI_MainMenuFood(GUI_LogIn guiLogin) {
        initComponents();
        this.guiLogin = guiLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FoodStandlbl = new javax.swing.JLabel();
        OrderFoodBtn = new javax.swing.JButton();
        FoodElementsBtn = new javax.swing.JButton();
        OrderFoodLbl = new javax.swing.JLabel();
        FoodElementsLbl = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        btnChangeStaffElements = new javax.swing.JButton();
        lblChangeStaffElements = new javax.swing.JLabel();
        AnalyticsButton = new javax.swing.JButton();
        lblFoodStaff = new javax.swing.JLabel();
        mBarFoodStaff = new javax.swing.JMenuBar();
        mItemFoodStaff = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FoodStandlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FoodStandlbl.setText("Concession Stand");

        OrderFoodBtn.setText("Enter");
        OrderFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderFoodBtnActionPerformed(evt);
            }
        });

        FoodElementsBtn.setText("Enter");
        FoodElementsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodElementsBtnActionPerformed(evt);
            }
        });

        OrderFoodLbl.setText("Order Food/Drink");

        FoodElementsLbl.setText("Concession Elements");

        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        btnChangeStaffElements.setText("Enter");
        btnChangeStaffElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStaffElementsActionPerformed(evt);
            }
        });

        lblChangeStaffElements.setText("Change Staff Elements");

        AnalyticsButton.setText("Analytics");
        AnalyticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsButtonActionPerformed(evt);
            }
        });

        lblFoodStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFoodStaff.setText("Food Staff");

        mBarFoodStaff.setToolTipText("");

        mItemFoodStaff.setText("About");

        jMenuItem1.setText("Food Staff");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mItemFoodStaff.add(jMenuItem1);

        mBarFoodStaff.add(mItemFoodStaff);

        setJMenuBar(mBarFoodStaff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AnalyticsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OrderFoodLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OrderFoodBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FoodElementsLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FoodElementsBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblChangeStaffElements, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(btnChangeStaffElements)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFoodStaff)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FoodStandlbl)
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(FoodStandlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(OrderFoodLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFoodStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OrderFoodBtn)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(FoodElementsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FoodElementsBtn)))
                        .addGap(44, 44, 44)
                        .addComponent(lblChangeStaffElements))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnChangeStaffElements)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutButton)
                    .addComponent(AnalyticsButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OrderFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderFoodBtnActionPerformed

        this.setVisible(false);
        new GUI_OrderFood(this).setVisible(true);
    }//GEN-LAST:event_OrderFoodBtnActionPerformed

    private void FoodElementsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodElementsBtnActionPerformed

        this.setVisible(false);
        new GUI_ConcessionElements(this).setVisible(true);
    }//GEN-LAST:event_FoodElementsBtnActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.guiLogin.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void btnChangeStaffElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStaffElementsActionPerformed
        // TODO add your handling code here:
        GUI_StaffElements guiStaffElements = new GUI_StaffElements(this);
        
        this.setVisible(false);
        
        guiStaffElements.setVisible(true);
    }//GEN-LAST:event_btnChangeStaffElementsActionPerformed

    private void AnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButtonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);

        GUI_AnalyticsMenu guiAnalyticsMenu = new GUI_AnalyticsMenu(this);
        
        
    }//GEN-LAST:event_AnalyticsButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        new GUI_AboutFoodStaff().setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MainMenuFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticsButton;
    private javax.swing.JButton FoodElementsBtn;
    private javax.swing.JLabel FoodElementsLbl;
    private javax.swing.JLabel FoodStandlbl;
    private javax.swing.JButton OrderFoodBtn;
    private javax.swing.JLabel OrderFoodLbl;
    private javax.swing.JButton btnChangeStaffElements;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblChangeStaffElements;
    private javax.swing.JLabel lblFoodStaff;
    private javax.swing.JButton logOutButton;
    private javax.swing.JMenuBar mBarFoodStaff;
    private javax.swing.JMenu mItemFoodStaff;
    // End of variables declaration//GEN-END:variables
}
