/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author lccra
 */
public class GUI_MainMenuTicket extends javax.swing.JFrame {
    private GUI_LogIn guiLogin;
    
    /**
     * Creates new form GUI_MainMenuTicket
     */
    public GUI_MainMenuTicket() {
        initComponents();
    }

    public GUI_MainMenuTicket(GUI_LogIn guiLogin) {
        initComponents();
        this.guiLogin = guiLogin;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTicketStaffFrame = new javax.swing.JLabel();
        btnOrderMovieTicket = new javax.swing.JButton();
        lblOrderTicket = new javax.swing.JLabel();
        lblChangeMovieElements = new javax.swing.JLabel();
        btnChangeMovieElements = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        lblChangeStaffElements = new javax.swing.JLabel();
        btnChangeStaffElements = new javax.swing.JButton();
        AnalyticsButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAboutTicketStaff = new javax.swing.JMenu();
        mItemTicketStaff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTicketStaffFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTicketStaffFrame.setText("Ticket Staff");

        btnOrderMovieTicket.setText("Enter");
        btnOrderMovieTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMovieTicketActionPerformed(evt);
            }
        });

        lblOrderTicket.setText("Order Movie Ticket");

        lblChangeMovieElements.setText("Change Movie Elements");

        btnChangeMovieElements.setText("Enter");
        btnChangeMovieElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeMovieElementsActionPerformed(evt);
            }
        });

        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        lblChangeStaffElements.setText("Change Staff Elements");

        btnChangeStaffElements.setText("Enter");
        btnChangeStaffElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStaffElementsActionPerformed(evt);
            }
        });

        AnalyticsButton.setText("Analytics");
        AnalyticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsButtonActionPerformed(evt);
            }
        });

        mAboutTicketStaff.setText("About");

        mItemTicketStaff.setText("Ticket Staff");
        mItemTicketStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemTicketStaffActionPerformed(evt);
            }
        });
        mAboutTicketStaff.add(mItemTicketStaff);

        jMenuBar1.add(mAboutTicketStaff);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChangeMovieElements)
                    .addComponent(lblOrderTicket)
                    .addComponent(lblChangeStaffElements, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrderMovieTicket)
                    .addComponent(btnChangeMovieElements)
                    .addComponent(btnChangeStaffElements))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblTicketStaffFrame))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AnalyticsButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTicketStaffFrame)
                .addGap(4, 4, 4)
                .addComponent(logOutButton)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderMovieTicket)
                    .addComponent(lblOrderTicket))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChangeMovieElements)
                    .addComponent(btnChangeMovieElements))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChangeStaffElements)
                    .addComponent(btnChangeStaffElements))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(AnalyticsButton)
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(477, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderMovieTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMovieTicketActionPerformed
        
        this.setVisible(false);
        new GUI_OrderMovieTicket(this).setVisible(true);
        
    }//GEN-LAST:event_btnOrderMovieTicketActionPerformed

    private void btnChangeMovieElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeMovieElementsActionPerformed

        this.setVisible(false);
        new GUI_MovieElements(this).setVisible(true);
        
    }//GEN-LAST:event_btnChangeMovieElementsActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.guiLogin.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void btnChangeStaffElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStaffElementsActionPerformed
        // TODO add your handling code here:
        GUI_StaffElements guiStaffElements = new GUI_StaffElements(this);
        
        this.setVisible(false);
        
        guiStaffElements.setVisible(true);
        
    }//GEN-LAST:event_btnChangeStaffElementsActionPerformed

    private void AnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        GUI_AnalyticsMenu guiAnalyticsMenu = new GUI_AnalyticsMenu(this);
        
    }//GEN-LAST:event_AnalyticsButtonActionPerformed

    private void mItemTicketStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemTicketStaffActionPerformed

        new GUI_AboutTicketStaff().setVisible(true);

    }//GEN-LAST:event_mItemTicketStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenuTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MainMenuTicket().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticsButton;
    private javax.swing.JButton btnChangeMovieElements;
    private javax.swing.JButton btnChangeStaffElements;
    private javax.swing.JButton btnOrderMovieTicket;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblChangeMovieElements;
    private javax.swing.JLabel lblChangeStaffElements;
    private javax.swing.JLabel lblOrderTicket;
    private javax.swing.JLabel lblTicketStaffFrame;
    private javax.swing.JButton logOutButton;
    private javax.swing.JMenu mAboutTicketStaff;
    private javax.swing.JMenuItem mItemTicketStaff;
    // End of variables declaration//GEN-END:variables
}
