import java.io.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Scanner;
import util.Path;

public class Analytics {
	private LocalDateTime timePeriodStart;
	private LocalDateTime timePeriodEnd;
	private Scanner input;

	/**
	 * Constructs an Analytics object with a specified start time for the reporting period.
	 * The end time is set to the current time.
	 *
	 */
	public Analytics() {
		this.timePeriodStart = null;
		this.timePeriodEnd = LocalDateTime.now(ZoneId.of("US/Mountain"));
		this.input = new Scanner(System.in);
	}

	/**
	 * Constructs an Analytics object with a specified start time for the reporting period.
	 * The end time is set to the current time.
	 *
	 * @param timePeriodStart The start time for the report period.
	 */
	public Analytics(LocalDateTime timePeriodStart) {
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = LocalDateTime.now(ZoneId.of("US/Mountain"));
		this.input = new Scanner(System.in);
	}

	/**
	 * Constructs an Analytics object with specified start and end times for the reporting period.
	 *
	 * @param timePeriodStart The start time for the report period.
	 * @param timePeriodEnd The end time for the report period.
	 */
	public Analytics(LocalDateTime timePeriodStart, LocalDateTime timePeriodEnd) {
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;
		this.input = new Scanner(System.in);
	}

	/**
	 * Returns the time period for the report, including start and end times.
	 *
	 * @return A Pair containing the start and end times of the report.
	 */
	public LocalDateTime[] getTimePeriod() {
		LocalDateTime[] dateTime = {this.timePeriodStart, this.timePeriodEnd};
		return dateTime;
	}

	/**
	 * Sets the start time for the report period and resets the end time to the current time.
	 *
	 * @param timePeriodStart The new start time for the report period.
	 */
	public void setTimePeriod(LocalDateTime timePeriodStart){
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = LocalDateTime.now(ZoneId.of("US/Mountain"));
	}

	/**
	 * Sets both the start and end times for the report period.
	 *
	 * @param timePeriodStart The new start time for the report period.
	 * @param timePeriodEnd The new end time for the report period.
	 */
	public void setTimePeriod(LocalDateTime timePeriodStart, LocalDateTime timePeriodEnd){
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;
	}

	/**
	 * Checks if a time period has been set.
	 *
	 * @return True if both start and end times are set; false otherwise.
	 */
	public boolean hasTimePeriod() {
		return !(timePeriodStart==null || timePeriodEnd==null);
	}

	/**
	 * Prompts the user to select and generate a report based on the available options.
	 */
	public void generateReport() {
		byte option;
		do {
			System.out.println("Which report would you like to generate?");
			System.out.println("1. Ticket sales report");
			System.out.println("2. Food sales report");
			System.out.println("3. Inventory report");
			System.out.println("4. Item order history report");
			option = input.nextByte();
			if (option<0 || option>4) {
				System.out.println("Invalid option!");
			}
		} while (option<0 || option>4);
		switch (option) {
			case 1:
				generateTicketSalesReport();
				break;
			case 2:
				generateFoodSalesReport();
				break;
			case 3:
				generateInventoryReport();
				break;
			case 4:
				generateItemOrderReport();
				break;
			default:
				System.out.println("No report to be generated!");
		}
	}

	/**
	 * Generates a ticket sales report. (Implementation to be added later.)
	 */
	private void generateTicketSalesReport() {
		// implement after ticket sales has been properly handled
	}

	/**
	 * Generates a food sales report for the specified time period.
	 * Reads data from a file and displays it in a tabular format.
	 */
	private void generateFoodSalesReport() {
		/*
		 * The report generated by the generateFoodSalesReport method is formatted as follows:
		 *
		 * 1. The report header is displayed with the following columns:
		 * 	  - Payment ID
		 *    - Date & Time
		 *    - Food Name
		 *    - Quantity
		 *    - Price
		 *
		 * 2. Each order is printed in the following format:
		 *    - The order's timestamp (Date & Time)
		 *    - The food item name
		 *    - The quantity of the food item ordered
		 *    - The price for the quantity of the food item ordered
		 *
		 * 3. If there are multiple food items in a single order,
		 * each food item is displayed on a new line under the same order with its respective details.
		 *
		 * 4. After each order, a separator line is printed, and the total price for the order is displayed.
		 *
		 * Example:
		 *
		 * Payment ID		|Date & Time            |Food Name         |Quantity       |Price
		 * -----------------------------------------------------------------------------------
		 * 2025-03-07-001	|2025-03-07T10:30:00    |Burger            |2              |$10.00
		 *         		    |               		|Fries             |1              |$2.50
		 * -----------------------------------------------------------------------------------
		 *                      									  totalPrice       |$12.50
		 * ------------------------------------------------------------------------------------
		 *
		 * 5. The report is filtered based on the time period, if specified.
		 * Orders outside the specified time period will not appear in the report.
		 */

		try (BufferedReader reader = new BufferedReader(new FileReader(Path.FOOD_SALES_REPORT_PATH))) {
			System.out.println("Below is the food sales report for the specified time period: ");
			System.out.println("Payment ID\t\t|Date & Time\t\t|Food Name\t\t|Quantity\t\t|Price");
			System.out.println("-----------------------------------------------------------------");
			String line;
			while ((line = reader.readLine()) != null) {
				String orderInfo = line.split(";")[0];
				String orderList = line.split(";")[1];

				String paymentId = orderInfo.split(",")[0];
				LocalDateTime time = LocalDateTime.parse(orderInfo.split(",")[1]);
				String totalPrice = orderInfo.split(",")[2];

				String[] orderArray = orderList.split(",");
				if (this.hasTimePeriod() && time.isAfter(this.timePeriodStart) && time.isBefore(this.timePeriodEnd)) {
					System.out.println(paymentId + "\t\t|" + time + "\t\t|" + orderArray[0] + "\t\t|" + orderArray[1] + "\t\t|" + orderArray[2]);

					if (orderArray.length > 3) {
						for (int i=3; i<orderArray.length; i+=3) {
							System.out.println("\t\t\t\t\t\t|" + orderArray[i] + "\t\t|" + orderArray[i+1]);
						}
					}
					System.out.println("-----------------------------------------------------------------");
					System.out.println("\t\t\t\t\t\ttotalPrice\t\t|" + totalPrice);
					System.out.println("-----------------------------------------------------------------");
				}
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}

	/**
	 * Generates an inventory report for the current time.
	 * Reads data from a file and displays the inventory items and quantities.
	 */
	private void generateInventoryReport() {
		/*
		 * The report generated by the generateInventoryReport method is formatted as follows:
		 *
		 * 1. The report header is displayed with the following columns:
		 *    - Item Name
		 *    - Quantity
		 *
		 * 2. Each line of the report represents an item in the inventory, formatted as:
		 *    - The name of the item
		 *    - The quantity of the item in stock
		 *
		 * 3. The items are displayed in the following format:
		 *    - The item name
		 *    - The quantity of the item in the inventory
		 *
		 * Example:
		 *
		 * Item Name            |Quantity
		 * --------------------------------------------------
		 * Burger               |50
		 * Fries                |100
		 * Coke					|75
		 *
		 * 4. The report reads data from the inventory report file
		 * and prints each item with its corresponding quantity.
		 *
		 * 5. The report is printed as a simple tabular list with item names and quantities.
		 */

		try (BufferedReader reader = new BufferedReader(new FileReader(Path.INVENTORY_REPORT_PATH))) {
			System.out.println("Below is the current content of the inventory: ");
			System.out.println("Item Name\t\t|Quantity");
			System.out.println("--------------------------------------------------");
			String line;
			while ((line = reader.readLine()) != null) {
				String itemName = line.split(",")[0];
				short quantity = Short.parseShort(line.split(",")[1]);
				System.out.println(itemName + "\t\t|" + quantity);
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}

	/**
	 * Generates a report of the item order history for the specified time period.
	 * Reads data from a file and displays the item order history.
	 */
	private void generateItemOrderReport() {
		/*
		 * The report generated by the generateItemOrderReport method is formatted as follows:
		 *
		 * 1. The report header is displayed with the following columns:
		 *    - Date & Time
		 *    - Item Name
		 *    - Quantity Bought
		 *    - Total Price
		 *
		 * 2. Each line of the report represents an item order, formatted as:
		 *    - The date and time when the order was made
		 *    - The name of the item ordered
		 *    - The quantity of the item ordered
		 *    - The total price for that order
		 *
		 * 3. The report filters the orders based on the specified time period.
		 * Only the orders that fall within the time period are displayed.
		 *
		 * Example:
		 *
		 * Date & Time             |Item Name            |Quantity Bought |TotalPrice
		 * ------------------------------------------------------------------------
		 * 2025-03-01T14:00:00     |Burger               |10              |150
		 * 2025-03-01T15:30:00     |Fries                |20              |100
		 *
		 * 4. The report reads data from the item order report file
		 * and prints each order with the corresponding details.
		 *
		 * 5. The report is printed as a simple tabular list
		 * with date, item name, quantity, and total price.
		 */

		try (BufferedReader reader = new BufferedReader(new FileReader(Path.ITEM_ORDER_REPORT_PATH))) {
			System.out.println("Below is the inventory item order history: ");
			System.out.println("Date & Time\t\t|Item Name\t\t|Quantity Bought\t\t|TotalPrice");
			System.out.println("-----------------------------------------------------------------");
			String line;
			while ((line = reader.readLine()) != null) {
				LocalDateTime time = LocalDateTime.parse(line.split(",")[0]);
				String itemName = line.split(",")[1];
				short quantity = Short.parseShort(line.split(",")[2]);
				short totalPrice = Short.parseShort(line.split(",")[3]);
				if (this.hasTimePeriod() && time.isAfter(this.timePeriodStart) && time.isBefore(this.timePeriodEnd)) {
					System.out.println(time + "\t\t|" + itemName + "\t\t|" + quantity + "\t\t|" + totalPrice);
				}
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}

	/**
	 * Prompts the user to select and export a report based on the available options.
	 */
	public void exportReport() {
		byte option;
		do {
			System.out.println("Which report would you like to export?");
			System.out.println("1. Ticket sales report");
			System.out.println("2. Food sales report");
			System.out.println("3. Inventory report");
			System.out.println("4. Item order history report");
			option = input.nextByte();
			if (option<0 || option>4) {
				System.out.println("Invalid option!");
			}
		} while (option<0 || option>4);
		switch (option) {
			case 1:
				this.exportTicketSalesReport();
				break;
			case 2:
				exportFoodSalesReport();
				break;
			case 3:
				exportInventoryReport();
				break;
			case 4:
				exportItemOrderReport();
				break;
			default:
				System.out.println("No report to be exported!");
		}
	}

	/**
	 * Exports the ticket sales report. (Implementation to be added later.)
	 */
	private void exportTicketSalesReport() {
		// implement after ticket sales has been properly handled
	}

	/**
	 * Exports the food sales report for the specified time period to a file.
	 */
	private void exportFoodSalesReport() {
		// format is the same as generateFoodSalesReport
		String foodSalesExportPath = Path.FOOD_SALES_EXPORT_PATH + "foodSales:" + this.timePeriodStart + "->" + this.timePeriodEnd + ".txt";
		try (BufferedReader reader = new BufferedReader(new FileReader(Path.FOOD_SALES_REPORT_PATH));
			 BufferedWriter writer = new BufferedWriter(new FileWriter(foodSalesExportPath, true))) {
			writer.write("Below is the food sales report for the specified time period: ");
			writer.newLine();
			writer.write("Payment ID\t\t|Date & Time\t\t|Food Name\t\t|Quantity\t\t|Price");
			writer.newLine();
			writer.write("-----------------------------------------------------------------");
			writer.newLine();
			String line;
			while ((line = reader.readLine()) != null) {
				String orderInfo = line.split(";")[0];
				String orderList = line.split(";")[1];

				String paymentId = orderInfo.split(",")[0];
				LocalDateTime time = LocalDateTime.parse(orderInfo.split(",")[1]);
				String totalPrice = orderInfo.split(",")[2];

				String[] orderArray = orderList.split(",");
				if (this.hasTimePeriod() && time.isAfter(this.timePeriodStart) && time.isBefore(this.timePeriodEnd)) {
					writer.write(paymentId + "\t\t|" + time + "\t\t|" + orderArray[0] + "\t\t|" + orderArray[1] + "\t\t|" + orderArray[2]);
					writer.newLine();

					if (orderArray.length > 3) {
						for (int i=3; i<orderArray.length; i+=3) {
							writer.write("\t\t\t\t\t\t|" + orderArray[i] + "\t\t|" + orderArray[i+1]);
							writer.newLine();
						}
					}
					writer.write("-----------------------------------------------------------------");
					writer.newLine();
					writer.write("\t\t\t\t\t\ttotalPrice\t\t|" + totalPrice);
					writer.newLine();
					writer.write("-----------------------------------------------------------------");
				}
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}

	/**
	 * Exports the inventory report to a file for the current time.
	 */
	private void exportInventoryReport() {
		// format is the same as generateInventoryReport
		String inventoryExportFilePath = Path.INVENTORY_EXPORT_PATH + "inventory:" + LocalDateTime.now() + ".txt";
		try (BufferedReader reader = new BufferedReader(new FileReader(Path.INVENTORY_REPORT_PATH));
			 BufferedWriter writer = new BufferedWriter(new FileWriter(inventoryExportFilePath, true))){
			writer.write("Below is the content of the inventory as of " + LocalDateTime.now() + ":");
			writer.newLine();
			writer.write("Item Name\t\t|Quantity");
			writer.newLine();
			writer.write("--------------------------------------------------");
			writer.newLine();
			String line;
			while ((line = reader.readLine()) != null) {
				String itemName = line.split(",")[0];
				short quantity = Short.parseShort(line.split(",")[1]);
				writer.write(itemName + "\t\t|" + quantity);
				writer.newLine();
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}

	/**
	 * Exports the item order history report to a file for the specified time period.
	 */
	private void exportItemOrderReport() {
		// format is the same as generateItemOrderReport
		String itemOrderExportPath = Path.ITEM_ORDER_EXPORT_PATH + "itemOrderHistory:" + this.timePeriodStart + "->" + this.timePeriodEnd + ".txt";
		try (BufferedReader reader = new BufferedReader(new FileReader(Path.ITEM_ORDER_REPORT_PATH));
			 BufferedWriter writer = new BufferedWriter(new FileWriter(itemOrderExportPath, true))) {
			writer.write("Below is the inventory item order history: ");
			writer.newLine();
			writer.write("Date & Time\t\t|Item Name\t\t|Quantity Bought\t\t|TotalPrice");
			writer.newLine();
			writer.write("-----------------------------------------------------------------");
			writer.newLine();
			String line;
			while ((line = reader.readLine()) != null) {
				LocalDateTime time = LocalDateTime.parse(line.split(",")[0]);
				String itemName = line.split(",")[1];
				short quantity = Short.parseShort(line.split(",")[2]);
				short totalPrice = Short.parseShort(line.split(",")[3]);
				if (this.hasTimePeriod() && time.isAfter(this.timePeriodStart) && time.isBefore(this.timePeriodEnd)) {
					writer.write(time + "\t\t|" + itemName + "\t\t|" + quantity + "\t\t|" + totalPrice);
					writer.newLine();
				}
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		}
	}
}
